version: "3.8"

services:
  gateway_api:
    image: krakend
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/krakend.json:/etc/krakend/krakend.json
    networks:
      - service

  service_auth_user:
    image: daffa4lif/service-user-auth
    container_name: service-user-auth
    env_file:
      - ./services/auth-user/.env
    volumes:
      - ./services/auth-user/keys:/app/keys
    networks:
      - service
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    env_file:
      - ./mongo/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - service

networks:
  service:

volumes:
  mongo_data:
